### PR TITLE
* show x of total events in Progress / * handle events with no ThumbnailImage

### PR DESCRIPTION
**Pull request by kongomongo**
heya, can you have a look at this? kept crashing because of an event (of 480) with no thumbnailimage. 

Also added a x of y counter display for longer wait times...

PS: Do you think it would be possible to have a fullsize Video display without controls?

### CODE REVIEW

**Comment by grankko** [comment]
Great work! Was the thumbnail missing from your tesla drive? I haven't had that happening to me yet.

**Comment by grankko** [comment]
@kongomongo  - regarding fullsize, I could add an option to minimize the control panel

**Comment by kongomongo** [comment]
@grankko yes indeed I had the thumbnail missing on 2020.48. Not sure why.

a "hide/show" toggle for the controls to get fullsize would be awesome.

**Comment by grankko** [comment]
@kongomongo - hide/show controls toggle is in already in main :)

**Comment by kongomongo** [comment]
Awesome!

**Pull request merged**
